/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xogame;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Paramjeet Singh
 */
public class xomain extends javax.swing.JFrame {
    int pl=1;
    String p1name = "Player 1";
    String p2name = "Player 2";
    String p1sym = "";
    String p2sym = "";
    int round = 0;
    int p1 = 0;
    int p2 = 0;
    int draw = 0;
    String lastwinner = "";
    List pl1 = new ArrayList(){};
    List pl2 = new ArrayList(){};
    boolean c1play = false;
    boolean c2play = false;
    public xomain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        btn5 = new javax.swing.JToggleButton();
        btn7 = new javax.swing.JToggleButton();
        btn6 = new javax.swing.JToggleButton();
        btn4 = new javax.swing.JToggleButton();
        btn9 = new javax.swing.JToggleButton();
        btn8 = new javax.swing.JToggleButton();
        btn1 = new javax.swing.JToggleButton();
        btn2 = new javax.swing.JToggleButton();
        btn3 = new javax.swing.JToggleButton();
        turnlbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        s1cb = new javax.swing.JComboBox<>();
        startbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        quitbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        againbtn = new javax.swing.JButton();
        name2txt = new javax.swing.JTextField();
        go2 = new javax.swing.JButton();
        go1 = new javax.swing.JButton();
        name1txt = new javax.swing.JTextField();
        s2cb = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        humancb1 = new javax.swing.JCheckBox();
        humancb2 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        roundtxt = new javax.swing.JTextField();
        p1lbl = new javax.swing.JLabel();
        p1txt = new javax.swing.JTextField();
        p2txt = new javax.swing.JTextField();
        p2lbl = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        leadtxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lasttxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        drawtxt = new javax.swing.JTextField();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn5.setMnemonic('5');
        btn5.setEnabled(false);
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn7.setMnemonic('1');
        btn7.setEnabled(false);
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn6.setMnemonic('6');
        btn6.setEnabled(false);
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn4.setMnemonic('4');
        btn4.setEnabled(false);
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn9.setMnemonic('3');
        btn9.setEnabled(false);
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn8.setMnemonic('2');
        btn8.setEnabled(false);
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn1.setMnemonic('7');
        btn1.setEnabled(false);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn2.setMnemonic('8');
        btn2.setEnabled(false);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn3.setMnemonic('9');
        btn3.setEnabled(false);
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        turnlbl.setText(" Player 1");

        jLabel8.setText("Turn :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(turnlbl)))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(turnlbl)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Welcome to the XO Game");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Game Controls"));

        jLabel5.setText("Symbol");

        s1cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "O", "@", "#", "$", "&", "*" }));

        startbtn.setText("Start");
        startbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startbtnActionPerformed(evt);
            }
        });

        jLabel4.setText("Name");

        jLabel2.setText("Player 1");

        quitbtn.setText("Quit");
        quitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitbtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Player 2");

        againbtn.setText("Play Again");
        againbtn.setEnabled(false);
        againbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                againbtnActionPerformed(evt);
            }
        });

        go2.setText("Ready");
        go2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                go2ActionPerformed(evt);
            }
        });

        go1.setText("Ready");
        go1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                go1ActionPerformed(evt);
            }
        });

        s2cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O", "X", "@", "#", "$", "&", "*" }));

        jButton1.setText("New Game");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Status");

        humancb1.setSelected(true);
        humancb1.setText("Human");

        humancb2.setText("Human");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(name2txt, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jLabel4))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(name1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(s2cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(humancb2))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(s1cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(humancb1)))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(go2)
                                    .addComponent(go1)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel7))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(startbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(againbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(quitbtn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name1txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s1cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(go1)
                    .addComponent(humancb1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(name2txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s2cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(go2)
                    .addComponent(humancb2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startbtn)
                    .addComponent(againbtn)
                    .addComponent(quitbtn)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("ScoreBoard"));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Rounds Played");

        roundtxt.setEditable(false);
        roundtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        roundtxt.setText("0");

        p1lbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        p1lbl.setText("Player 1");

        p1txt.setEditable(false);
        p1txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p1txt.setText("0");

        p2txt.setEditable(false);
        p2txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        p2txt.setText("0");

        p2lbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        p2lbl.setText("Player 2");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Leading");

        leadtxt.setEditable(false);
        leadtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Last round Winner");

        lasttxt.setEditable(false);
        lasttxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Draw");

        drawtxt.setEditable(false);
        drawtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        drawtxt.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lasttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(leadtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(38, 38, 38))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(p1lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(7, 7, 7))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(p2lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(p2txt)
                            .addComponent(drawtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(roundtxt)
                            .addComponent(p1txt))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(roundtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p1lbl)
                    .addComponent(p1txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p2lbl)
                    .addComponent(p2txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(drawtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(leadtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lasttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    boolean wins(List list){
        if(list.contains("1") && list.contains("2") && list.contains("3")){
            return true;}
        else if(list.contains("4") && list.contains("5") && list.contains("6")){
            return true;}
        else if(list.contains("7") && list.contains("8") && list.contains("9")){
            return true;}
        else if(list.contains("1") && list.contains("4") && list.contains("7")){
            return true;}
        else if(list.contains("2") && list.contains("5") && list.contains("8")){
            return true;}
        else if(list.contains("3") && list.contains("6") && list.contains("9")){
            return true;}
        else if(list.contains("1") && list.contains("5") && list.contains("9")){
            return true;}
        else if(list.contains("3") && list.contains("5") && list.contains("7")){
            return true;}
        return false;
    }
    boolean checkwin(int pl){
        if(pl==1){
            if(wins(pl1)){
                JOptionPane.showMessageDialog(null,p1name+" Won the Game");
                over();
                p1++;
                round++;
                lastwinner=p1name;
                return true;
            }
        }else if(pl==2){
            if(wins(pl2)){
                JOptionPane.showMessageDialog(null,p2name+" Won the Game");
                over();
                p2++;
                round++;
                lastwinner=p2name;
                return true;
            }
        }
        refreshScore();
        return false;
    }
    void checkDraw(){
        if(Draw()){
            draw++;
            round++;
            JOptionPane.showMessageDialog(null,"The round ended in a Draw");
        }
        refreshScore();
    }
    boolean Draw(){
        int p1 = pl1.size();
        int p2 = pl2.size();
        if(!wins(pl1) && !wins(pl2) && (p1+p2)==9 ){
            return true;
        }
        return false;
    }
    void refreshScore(){
        roundtxt.setText(""+round);
        p1txt.setText(""+p1);
        p2txt.setText(""+p2);
        drawtxt.setText(""+draw);
        if(p1>p2){
            leadtxt.setText(p1name);
        }else if(p2>p1){
            leadtxt.setText(p2name);
        }
        lasttxt.setText(lastwinner);
    }
    void start(){
        btn1.setText("");
        btn2.setText("");
        btn3.setText("");
        btn4.setText("");
        btn5.setText("");
        btn6.setText("");
        btn7.setText("");
        btn8.setText("");
        btn9.setText("");
        btn1.setEnabled(true);
        btn2.setEnabled(true);
        btn3.setEnabled(true);
        btn4.setEnabled(true);
        btn5.setEnabled(true);
        btn6.setEnabled(true);
        btn7.setEnabled(true);
        btn8.setEnabled(true);
        btn9.setEnabled(true);
        btn1.setSelected(true);
        btn2.setSelected(true);
        btn3.setSelected(true);
        btn4.setSelected(true);
        btn5.setSelected(true);
        btn6.setSelected(true);
        btn7.setSelected(true);
        btn8.setSelected(true);
        btn9.setSelected(true);
    }
    void over(){
        btn1.setEnabled(false);
        btn2.setEnabled(false);
        btn3.setEnabled(false);
        btn4.setEnabled(false);
        btn5.setEnabled(false);
        btn6.setEnabled(false);
        btn7.setEnabled(false);
        btn8.setEnabled(false);
        btn9.setEnabled(false);
    }
    void startComputer(){
        if(pl==1){
                doBtn(getBtn(pl1,pl2));
        }else if(pl==2){
                doBtn(getBtn(pl2,pl1));
        }
    }
    void doBtn(int x){
        switch(x){
            case 1 : btn1.doClick();
            break;
            case 2 : btn2.doClick();
            break;
            case 3 : btn3.doClick();
            break;
            case 4 : btn4.doClick();
            break;
            case 5 : btn5.doClick();
            break;
            case 6 : btn6.doClick();
            break;
            case 7 : btn7.doClick();
            break;
            case 8 : btn8.doClick();
            break;
            case 9 : btn9.doClick();
            break;
        }
    }
    int getBtn(List plc,List plx){
        //plx=Opposite Player,  plc=Current Player
        if(plx.contains("1") && plx.contains("2") && (!plx.contains("3") && !plc.contains("3"))){
            return 3;
        }else if(plx.contains("2") && plx.contains("3") && (!plx.contains("1") && !plc.contains("1"))){
            return 1;
        }else if(plx.contains("3") && plx.contains("1") && (!plx.contains("2") && !plc.contains("2"))){
            return 2;
        }else if(plx.contains("4") && plx.contains("5") && (!plx.contains("6") && !plc.contains("6"))){
            return 6;
        }else if(plx.contains("5") && plx.contains("6") && (!plx.contains("4") && !plc.contains("4"))){
            return 4;
        }else if(plx.contains("6") && plx.contains("4") && (!plx.contains("5") && !plc.contains("5"))){
            return 5;
        }else if(plx.contains("7") && plx.contains("8") && (!plx.contains("9") && !plc.contains("9"))){
            return 9;
        }else if(plx.contains("8") && plx.contains("9") && (!plx.contains("7") && !plc.contains("7"))){
            return 7;
        }else if(plx.contains("9") && plx.contains("7") && (!plx.contains("8") && !plc.contains("8"))){
            return 8;
        }else if(plx.contains("1") && plx.contains("4") && (!plx.contains("7") && !plc.contains("7"))){
            return 7;
        }else if(plx.contains("4") && plx.contains("7") && (!plx.contains("1") && !plc.contains("1"))){
            return 1;
        }else if(plx.contains("7") && plx.contains("1") && (!plx.contains("4") && !plc.contains("4"))){
            return 4;
        }else if(plx.contains("2") && plx.contains("5") && (!plx.contains("8") && !plc.contains("8"))){
            return 8;
        }else if(plx.contains("5") && plx.contains("8") && (!plx.contains("2") && !plc.contains("2"))){
            return 2;
        }else if(plx.contains("8") && plx.contains("2") && (!plx.contains("5") && !plc.contains("5"))){
            return 5;
        }else if(plx.contains("3") && plx.contains("6") && (!plx.contains("9") && !plc.contains("9"))){
            return 9;
        }else if(plx.contains("6") && plx.contains("9") && (!plx.contains("3") && !plc.contains("3"))){
            return 3;
        }else if(plx.contains("9") && plx.contains("3") && (!plx.contains("6") && !plc.contains("6"))){
            return 6;
        }else if(plx.contains("1") && plx.contains("5") && (!plx.contains("9") && !plc.contains("9"))){
            return 9;
        }else if(plx.contains("5") && plx.contains("9") && (!plx.contains("1") && !plc.contains("1"))){
            return 1;
        }else if(plx.contains("9") && plx.contains("1") && (!plx.contains("5") && !plc.contains("5"))){
            return 5;
        }else if(plx.contains("3") && plx.contains("5") && (!plx.contains("7") && !plc.contains("7"))){
            return 7;
        }else if(plx.contains("5") && plx.contains("7") && (!plx.contains("3") && !plc.contains("3"))){
            return 3;
        }else if(plx.contains("7") && plx.contains("3") && (!plx.contains("5") && !plc.contains("5"))){
            return 5;
        }
        return random();
    }
    int random(){
        if(!pl1.contains("1")&& !pl2.contains("1")){
            return 1;
        }else if(!pl1.contains("2")&& !pl2.contains("2")){
            return 2;
        }else if(!pl1.contains("3")&& !pl2.contains("3")){
            return 3;
        }else if(!pl1.contains("4")&& !pl2.contains("4")){
            return 4;
        }else if(!pl1.contains("5")&& !pl2.contains("5")){
            return 5;
        }else if(!pl1.contains("6")&& !pl2.contains("6")){
            return 6;
        }else if(!pl1.contains("7")&& !pl2.contains("7")){
            return 7;
        }else if(!pl1.contains("8")&& !pl2.contains("8")){
            return 8;
        }else if(!pl1.contains("9")&& !pl2.contains("9")){
            return 9;
        }
        return 0;
    }
    void updateTurn(){
        if(pl==1){
            turnlbl.setText(p1name);
        }else if(pl==2){
            turnlbl.setText(p2name);
        }
    }
    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        if(pl==1){
            btn4.setText(p1sym);
            pl1.add("4");
            checkwin(pl);
            checkDraw();
            pl=2;
            if(c2play){startComputer();}
        }
        else if(pl==2){
            btn4.setText(p2sym);
            pl2.add("4");
            checkwin(pl);
            checkDraw();
            pl=1;
            if(c1play){startComputer();}
        }
        btn4.setEnabled(false);
        updateTurn();
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        if(pl==1){
            btn5.setText(p1sym);
            pl1.add("5");
            checkwin(pl);
            checkDraw();
            pl=2;
            if(c2play){startComputer();}
        }
        else if(pl==2){
            btn5.setText(p2sym);
            pl2.add("5");
            checkwin(pl);
            checkDraw();
            pl=1;
            if(c1play){startComputer();}
        }
        btn5.setEnabled(false);
        updateTurn();
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        if(pl==1){
            btn6.setText(p1sym);
            pl1.add("6");
            checkwin(pl);
            checkDraw();
            pl=2;
            if(c2play){startComputer();}
        }
        else if(pl==2){
            btn6.setText(p2sym);
            pl2.add("6");
            checkwin(pl);
            checkDraw();
            pl=1;
            if(c1play){startComputer();}
        }
        btn6.setEnabled(false);
        updateTurn();
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        if(pl==1){
            btn7.setText(p1sym);
            pl1.add("7");
            checkwin(pl);
            checkDraw();
            pl=2;
            if(c2play){startComputer();}
        }
        else if(pl==2){
            btn7.setText(p2sym);
            pl2.add("7");
            checkwin(pl);
            checkDraw();
            pl=1;
            if(c1play){startComputer();}
        }
        btn7.setEnabled(false);
        updateTurn();
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        if(pl==1){
            btn8.setText(p1sym);
            pl1.add("8");
            checkwin(pl);
            checkDraw();
            pl=2;
            if(c2play){startComputer();}
        }
        else if(pl==2){
            btn8.setText(p2sym);
            pl2.add("8");
            checkwin(pl);
            checkDraw();
            pl=1;
            if(c1play){startComputer();}
        }
        btn8.setEnabled(false);
        updateTurn();
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        if(pl==1){
            btn9.setText(p1sym);
            pl1.add("9");
            checkwin(pl);
            checkDraw();
            pl=2;
            if(c2play){startComputer();}
        }
        else if(pl==2){
            btn9.setText(p2sym);
            pl2.add("9");
            checkwin(pl);
            checkDraw();
            pl=1;
            if(c1play){startComputer();}
        }
        btn9.setEnabled(false);
        updateTurn();
    }//GEN-LAST:event_btn9ActionPerformed

    private void startbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startbtnActionPerformed
        if(!go1.isEnabled() && !go2.isEnabled()){
            start();
            startbtn.setEnabled(false);
            againbtn.setEnabled(true);
        }
        if(c1play){
            startComputer();
        }
        updateTurn();
    }//GEN-LAST:event_startbtnActionPerformed

    private void quitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitbtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitbtnActionPerformed

    private void againbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_againbtnActionPerformed
        pl1.removeAll(pl1);
        pl2.removeAll(pl2);
        pl=1;
        start();
        if(c1play){
            startComputer();
        }
        updateTurn();
    }//GEN-LAST:event_againbtnActionPerformed

    private void go1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_go1ActionPerformed
        String sym = (String) s1cb.getSelectedItem();
        if(!sym.equals(p2sym)){
            p1sym = sym;
            String name = name1txt.getText();
            if(!name.equals(""))
                p1name=name;
            if(!humancb1.isSelected()){
                p1name = "Computer 2";
                c1play=true;
            }
            name1txt.setEnabled(false);
            s1cb.setEnabled(false);
            go1.setEnabled(false);
            humancb1.setEnabled(false);
            p1lbl.setText(p1name);
        }else{
            JOptionPane.showMessageDialog(null,"Player 1, please choose another symbol");
        }
        
    }//GEN-LAST:event_go1ActionPerformed

    private void go2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_go2ActionPerformed
        String sym = (String) s2cb.getSelectedItem();
        if(!sym.equals(p1sym)){
            p2sym=sym;
            String name = name2txt.getText();
            if(!name.equals(""))
                p2name=name;
            if(!humancb2.isSelected()){
                p2name = "Computer";
                c2play=true;
            }
            name2txt.setEnabled(false);
            s2cb.setEnabled(false);
            go2.setEnabled(false);
            humancb2.setEnabled(false);
            p2lbl.setText(p2name);
        }else{
            JOptionPane.showMessageDialog(null,"Player 2, please choose another symbol");
        }
        
    }//GEN-LAST:event_go2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new xomain().setVisible(true);
            }
        });
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        if(pl==1){
            btn1.setText(p1sym);
            pl1.add("1");
            checkwin(pl);
            checkDraw();
            pl=2;
            if(c2play){startComputer();}
        }
        else if(pl==2){
            btn1.setText(p2sym);
            pl2.add("1");
            checkwin(pl);
            checkDraw();
            pl=1;
            if(c1play){startComputer();}
        }
        btn1.setEnabled(false);
        updateTurn();
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        if(pl==1){
            btn2.setText(p1sym);
            pl1.add("2");
            checkwin(pl);
            checkDraw();
            pl=2;
            if(c2play){startComputer();}
        }
        else if(pl==2){
            btn2.setText(p2sym);
            pl2.add("2");
            checkwin(pl);
            checkDraw();
            pl=1;
            if(c1play){startComputer();}
        }
        btn2.setEnabled(false);
        updateTurn();
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        if(pl==1){
            btn3.setText(p1sym);
            pl1.add("3");
            checkwin(pl);
            checkDraw();
            pl=2;
            if(c2play){startComputer();}
        }
        else if(pl==2){
            btn3.setText(p2sym);
            pl2.add("3");
            checkwin(pl);
            checkDraw();
            pl=1;
            if(c1play){startComputer();}
        }
        btn3.setEnabled(false);
        updateTurn();
    }//GEN-LAST:event_btn3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(xomain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(xomain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(xomain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(xomain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new xomain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton againbtn;
    private javax.swing.JToggleButton btn1;
    private javax.swing.JToggleButton btn2;
    private javax.swing.JToggleButton btn3;
    private javax.swing.JToggleButton btn4;
    private javax.swing.JToggleButton btn5;
    private javax.swing.JToggleButton btn6;
    private javax.swing.JToggleButton btn7;
    private javax.swing.JToggleButton btn8;
    private javax.swing.JToggleButton btn9;
    private javax.swing.JTextField drawtxt;
    private javax.swing.JButton go1;
    private javax.swing.JButton go2;
    private javax.swing.JCheckBox humancb1;
    private javax.swing.JCheckBox humancb2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField lasttxt;
    private javax.swing.JTextField leadtxt;
    private javax.swing.JTextField name1txt;
    private javax.swing.JTextField name2txt;
    private javax.swing.JLabel p1lbl;
    private javax.swing.JTextField p1txt;
    private javax.swing.JLabel p2lbl;
    private javax.swing.JTextField p2txt;
    private javax.swing.JButton quitbtn;
    private javax.swing.JTextField roundtxt;
    private javax.swing.JComboBox<String> s1cb;
    private javax.swing.JComboBox<String> s2cb;
    private javax.swing.JButton startbtn;
    private javax.swing.JLabel turnlbl;
    // End of variables declaration//GEN-END:variables

}
